---
title: "homework 2"
author: "Benjamin Smith"
date: "9/21/2019"
output: pdf_document
---

```{r}

require(tidyverse)
require(ggplot2)

```

## 

```{r cars}
d <- c(0,0.5,1)
p <- cumsum(rep(0.01, 99))
# seq(0.01, 0.99, 0.01)
q <- 1-p
n = 10000
a = 1

alphas <- matrix(NA, nrow = length(p), ncol = length(d))
exp <- matrix(NA, nrow = length(p), ncol = length(d))

varG <- matrix(nrow = length(p), ncol=length(d), NA)
varGexp <- matrix(nrow = length(p), ncol=length(d), NA)
varA <- matrix(nrow = length(p), ncol=length(d), NA)

for (i in 1:length(p)){
  X=rbinom(n=n, prob=p[i], size =2)
  Z=1*(X==1)
  for ( j in 1:length(d)){
    G=ifelse(X==0, -a, ifelse(X==1, d[j], a))
    Y=G+rnorm(n=n, sd=sd(G))
    fitA <- lm(Y~X)$coef
    alpha <- fitA[2]
    alphas[i,j] <- cov(X,Y)/var(X)
    fitAD <- lm(Y~X+Z)$coef
    ahat <- fitAD[2]
    dhat <- fitAD[3]
    exp[i,j] <- a+d[j]*(q[i]-p[i])
    varG[i,j] <-  var(X*alpha)
    varA[i,j] <- var(X*ahat)
    # varG[i,j] <- (2*p[i]*q[i]*(ahat+dhat*(q[i]-p[i]))^2 + (2*p[i]*q[i]*dhat)^2)
    varGexp[i,j] <- (2*p[i]*q[i]*(a+d[j]*(q[i]-p[i]))^2 + (2*p[i]*q[i]*d[j])^2)
    #varA[i,j] <- 2*p[i]*q[i]*(alpha^2)
  }
}

plot(rep(p,2), c(varG[,1], varA[,1]), col = rep(c(1,2), each=length(p)), main = 'd = 0', 
     xlab = 'allele f', ylab = 'var(G), var(A) (red)') # d=0
plot(rep(p,2), c(varG[,2], varA[,2]), col = rep(c(1,2), each=length(p)), main = 'd = 0.5', 
     xlab = 'allele f', ylab = 'var(G), var(A) (red)') # d=0.5
plot(rep(p,2), c(varG[,3], varA[,3]), col = rep(c(1,2), each=length(p)), main = 'd = 1', 
     xlab = 'allele f', ylab = 'var(G), var(A) (red)') # d=1



# table(rbinom(1000, 2, .02))
length(varG)
length(p)

```

## Including Plots


```{r }
rm(list = ls())

load('SU_DATA.RData')

X=W
Y=y

I <- rep(1,length(Y))

Z=1*(X==1)

fm0 <- lm(Y~1)

an0A <- vector()
an0AD <- vector()
anDA <- vector()

for (i in 1:ncol(X)){
  fmA <- lm(Y~X[,i])
  fmAD <- lm(Y~X[,i]+Z[,i])
  an0A <- append(an0A,anova(fm0,fmA)$Pr[2])
  an0AD <- append(an0AD,anova(fm0,fmAD)$Pr[2])
  anDA <- append(anDA,anova(fmA,fmAD)$Pr[2])
  if (i %% 100 ==0) print(i)
}

log10an0A <- -log10(an0A)
log10an0AD <- -log10(an0AD)
log10anDA <- -log10(anDA)

plot(1:ncol(X),log10an0A)

for (i in 1:ncol(X)){
  fmAD[i] <- lm(Y~X[,i]+Z[,i])
  if (i %% 100 ==0) print(i)
}

lm0 <- fm0$coef
lmA <- fmA$coef
lmAD <- fmAD$coef

pA <- vector()
pAD <- vector()


for ( i in 1:length(fmA)){
  pA <- append(pA,anova(fm0,fmA[i])$Pr[2])
}

pA <- aov(fm0~fmA)$Pr[2]
pAD <- aov(fm0~fmAD)$Pr[2]
pD <- aov(fmA~fmAD)$Pr[2]

plot(1:length(pAD), -log10(pAD))

plot(1:length(pA), -log10(pA))

plot(1:length(pA), -log10(pA))


```